
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_41465_development

test:
  <<: *default
  database: furima_41465_test

production:
  <<: *default
  database: furima_41465_production
  username: furima_41465
  password: <%= ENV["FURIMA_41465_DATABASE_PASSWORD"] %>
